# Generated by Django 4.0.1 on 2022-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('exercise', models.CharField(max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
            ],
        ),
    ]
