# Generated by Django 4.0.1 on 2022-09-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
